# This pipeline aims to deploy table-level Role Assignments
name: $(SourceBranchName).$(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
    - scripts/Grant-LogAnalyticsTableRoles.ps1
    - input/logAnalyticsTableRoles.json

variables:
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: serviceConnection
    value: 'zm-p-g-spn-acrp-azdo-001'
  - name: logAnalyticsTableRolesConfigFilePath
    value: '$(System.DefaultWorkingDirectory)/input/logAnalyticsTableRoles.json'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: logAnalyticsTableRoles
    displayName: "Log Analytics Table Roles"
    jobs:
      - job: grantTableRoles
        displayName: "Grant Log Analytics Table Roles"
        steps:
          - task: AzurePowerShell@5
            displayName: Grant Log Analytics Table Roles
            inputs:
              azureSubscription: ${{variables.serviceConnection}}
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/Grant-LogAnalyticsTableRoles.ps1'
              ScriptArguments:
                -LogAnalyticsTableRolesConfigFilePath ${{variables.logAnalyticsTableRolesConfigFilePath}}
              azurePowerShellVersion: 'LatestVersion'