trigger: none

pool:
  vmImage: windows-latest

variables:
  - name: serviceConnection
    value: "<REPLACE>"

stages:
  - stage: logAnalyticsTableRoles
    displayName: "Log Analytics Table Roles"
    jobs:
      - job: grantTableRoles
        displayName: "Grant Log Analytics Table Roles"
        steps:
          - task: AzurePowerShell@5
            displayName: Grant Log Analytics Table Roles
            inputs:
              azureSubscription: ${{variables.serviceConnection}}
              ScriptType: 'FilePath'
              ScriptPath: "$(System.DefaultWorkingDirectory)/Manage Table-level Access on your Log Analytics Workspace/solutions/Grant-TableLevelAccess.ps1"
              ScriptArguments:
                -logAnalyticsTableRolesFilePath "$(System.DefaultWorkingDirectory)/Manage Table-level Access on your Log Analytics Workspace/parameters/parameters.json"
              azurePowerShellVersion: 'LatestVersion'